<?php

/**
 * CoreTrace
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
require_once(_ROOT.'code/models/Core/Base/Crude.php');
class CoreTrace extends Crude {
    function getBaseReadRecord($lbl) {
        if(!in_array($lbl,array('id','reference'))) {
            return parent::getBaseReadRecord($lbl);
        }
    }
    function getBaseActions(){
        return '';
    }
    function getBaseFormColumnFields(&$fields,$columns,$is_filter=false) {
        foreach($columns as $lbl=>$data) {
            $id=$this->identifier();
            if(strpos($lbl,'id')===false && strpos($lbl,'_by')===false) {
                $typeSize=explode("(",trim($data['type'],')'));
                $func="getBaseForm".ucfirst($typeSize[0]);
                if(method_exists($this,$func)) {
                    $fields->append($this->$func($lbl,ucfirst($typeSize[0]),$is_filter));
                }else {
                    $fields->append($this->getBaseFormInteger($lbl,ucfirst($typeSize[0]),$is_filter));
                }
            }
        }
    }
    
}