<?php

/**
 * CorePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CorePage extends Traceable
{
    function display(){
        
        $skin=$this->getSkin();
        echo $skin->resolve($this);
    }
    function getSkin(){
        
        if(count($this->PageSkinTemplate)){
           
            foreach($this->PageSkinTemplate as $key=>$triplet){
                if($triplet['template_id']==CURRENT_TEMPLATE_ID){
                    $skin=initObj('CoreSkin', $triplet['skin_id']);
                }
            }
        }
        if(empty ($skin)){
            $template=initObj('CoreTemplate', CURRENT_TEMPLATE_ID);
            $skin=$template->DefaultSkin;
        }
        return $skin;
    }
}