<?php

/**
 * CoreSkinZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreSkinZone extends Crude
{

}