<?php

/**
 * CorePermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CorePermission extends Crude {
    function getBaseRelationLabel() {
        $return=$this->name.' '.$this->object;
        if(!empty($this->object_id)) {
            $object=initObj($this->object,$this->object_id);
            $return.='->'.$object->getBaseRelationLabel();
        }

        return $return;
    }

}