<?php

/**
 * CoreWidget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreWidget extends Crude
{
	protected $zone;
	function construct() {
           if (getVal('zone')) {
                $this->zone=Doctrine_Core::getTable('CoreZone')->findOneBy('name',getVal('zone'));
           }
    }
    function resolve($Page,$Zone) {
            $widgetModel=initObj($this->Model->class_name,$this->id);
            $content=$widgetModel->resolve($Page,$Zone,$this);
            if($Zone->wrap) {
            $content=html('div')
                    ->class(WIDGET_DIV_CLASS." ".$this->Model->class_name)
                    ->id(WIDGET_DIV_ID.$this->id)
                    ->append($content);
            }
			//tracker
			//pr($_REQUEST);
            return $content;
    }
}