<?php

/**
 * CoreSkin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreSkin extends Crude
{
    function resolve($page) {
         
        $filename=_DESIGN_PATH.$this->path;
        if(file_exists($filename)) {
            
            $handle = fopen($filename, "r");
            $content = fread($handle, filesize($filename));
            fclose($handle);
            foreach ($this->Zones as $key=>$Zone) {
                $content=str_replace(SKIN_REPLACE_MASK.$Zone->name.SKIN_REPLACE_MASK, $Zone->resolve($page), $content);
            }
            echo $content;
        }else {
            throw new Exception($filename.' does not exist');
        }
    }
}