<?php

/**
 * CoreZone
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreZone extends Crude {
    function resolve($Page) {
        $content='';
        foreach ($this->Widgets as $key=>$Widget) {
            $content.=$Widget->resolve($Page,$this);
        }
        if($this->wrap) {
            $content=html('div')
                    ->class(ZONE_DIV_CLASS." ".$this->name)
                    ->id(ZONE_DIV_ID.$this->id)
					->data('book-id',getVal('book_id'))
                    ->append($content);
        }
        return $content;
    }
}