<?php

/**
 * CoreLabel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Content Management Platform
 * @subpackage CMP
 * @author     Dmitry "Les" Lesov <dmirty@mediaplatforms.ca>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreLabel extends Crude {

    function create() {
        if (isset($_GET["label"]) && ! $_POST) {
            $this->label = $_GET["label"];
        }
        return parent::create();
    }

    function getBaseListRedirect($action='explore', $id='') {
        $location=(isset($_SESSION['label_called_from']))?
            $_SESSION['label_called_from']:
            "?obj=" . get_class($this) . "&action=" . $action . $id;
        header("Location: ".$location);
        exit();
    }

    function getBaseForm() {
        if (!count($_POST)) {
            $_SESSION['label_called_from']=$_SERVER['HTTP_REFERER'];
        }
        return parent::getBaseForm();
    }

}

