CoreTemplateSkinModel:
  tableName: core_template_skin_model
  columns:
    template_id:
      type: integer(4)
      primary: true
      notnull: true
    skin_id:
      type: integer(4)
      primary: true
      notnull: true
    model_id:
      type: integer(4)
      primary: true
      notnull: true