CoreModel:
  tableName: core_model
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
    class_name:
      type: string(255)
    reference:
      type: string(255)

